### ISSUE TITLE
UI change for loginScreen

### ISSUE THREAD

**Issue by Pawan0411** [Pawan0411/Work-Scheduler#11]
Add logo to login screen
Make it more attractive.

**Comment by Shivam2498** [comment]
Can i get this assigned

**Comment by palakjadwani** [comment]
Taking

**Comment by palakjadwani** [comment]
where to see existing UI?

**Comment by Pawan0411** [comment]
@palakjadwani Please build in the app in your system to see the existing UI.

**Comment by palakjadwani** [comment]
Cannot find any .html file

**Comment by sdzshn3** [comment]
Android uses XML for layout.
File is in layout folder with name "activity_login.xml"

**Comment by Pawan0411** [comment]
Fixed.
