### ISSUE TITLE
Validate the phone Number

### ISSUE THREAD

**Issue by Pawan0411** [Pawan0411/Work-Scheduler#8]
Validate the phone number in `ChooseWorkCategoryActivity` class.

**Comment by JessieVela** [comment]
I can give this one a shot.

**Comment by Pawan0411** [comment]
@JessieVela work on this

**Comment by JessieVela** [comment]
Do we have to validate international numbers also?

**Comment by Pawan0411** [comment]
No.
Only Indian nunbers

**Comment by JessieVela** [comment]
Ohh good thing I asked. Okay.

**Comment by JessieVela** [comment]
how do I get past the login page? or bypass it?

**Comment by Pawan0411** [comment]
login via your Google Account

**Comment by JessieVela** [comment]
I tried but its not letting me. Just getting the error try again. This might be out of my level for understanding, so you can go ahead and un-assign me.

**Comment by Pawan0411** [comment]
@JessieVela You need to create a project in Firebase and then add the `google.json` file in your project location.

Then try to login.
Now you aren't able to login because you are from a different country.

Hope so you got it. 👍

**Comment by Pawan0411** [comment]
@priyanka-debnath  Good Work
